// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SalaCinemaAPI.Infra;

#nullable disable

namespace SalaCinemaAPI.Migrations
{
    [DbContext(typeof(ConnectionDB))]
    [Migration("20250122003518_Delta")]
    partial class Delta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SalaCinemaAPI.Entity.Filme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Diretor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Duracao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeFilme")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SalaIdSala")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SalaIdSala");

                    b.ToTable("Filmes");
                });

            modelBuilder.Entity("SalaCinemaAPI.Entity.Sala", b =>
                {
                    b.Property<int>("IdSala")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSala"));

                    b.Property<string>("NomeFilme")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumeroSala")
                        .HasColumnType("integer");

                    b.HasKey("IdSala");

                    b.ToTable("Salas");
                });

            modelBuilder.Entity("SalaCinemaAPI.Entity.Filme", b =>
                {
                    b.HasOne("SalaCinemaAPI.Entity.Sala", null)
                        .WithMany("Filmes")
                        .HasForeignKey("SalaIdSala");
                });

            modelBuilder.Entity("SalaCinemaAPI.Entity.Sala", b =>
                {
                    b.Navigation("Filmes");
                });
#pragma warning restore 612, 618
        }
    }
}
